import { Header } from "./components/header/header.js"
import { Sidebar } from "./components/sidebar/sidebar.js"
import { Player } from "./components/music-player/music-player.js"
import { PlaylistCard } from "./components/home/playlist-card.js"
import { Searchbar } from "./components/searchbar/searchbar.js"
import { SongCard } from "./components/song-card/song-card.js"
import { HomeContent } from "./components/home/home-content.js"
import { PlaylistFrontPage } from "./components/playlist-front-page/playlist-front-page.js"
import { SongPage } from "./components/song-page/song-page.js"
import { SongList } from "./components/home/songs-list.js"
import { SongCardHome } from "./components/home/song-card.js"
import { UserModal } from "./components/modals/user-modal.js"
import { PlaylistCard2 } from "./components/playlists/playlist-card.js"
import { PlaylistsContent } from "./components/playlists/playlists-cont.js"
import { Login } from "./components/login/login.js"
import { SignupModal } from "./components/modals/signup-modal.js"
import { AddPlaylistModal } from "./components/modals/add-playlist-modal.js"
import { SongMenu } from "./components/menus/songMenu.js"
import { SubscriptionContainer } from "./components/subscription-container/subscription-container.js"
import { SubscriptionCard } from "./components/subscription-card/subscription-card.js"
import { ProfileView } from "./components/profile-view/profile-view.js"
import { EditProfile } from "./components/edit-profile-view/edit-profile.js"

import page from "./routes/Router.js"
